NEWS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('newspaper.urls')),
    path("blog/", include("blog_app.urls")),
    path("api/v1/", include("api.urls")),
    path("accounts/login/", views.LoginView.as_view(), name="login"),
    path("accounts/logout/", views.LogoutView.as_view(), name="logout"),
    path("summernote/", include('django_summernote.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/urls.py
from django.urls import include, path
from rest_framework import routers

from api import views

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'groups', views.GroupViewSet)

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

blog_app/urls.py
from django.urls import path
from blog_app import views

app_name = "blog"


urlpatterns = [
    path("", views.PostListView.as_view(), name="post-list"),
    #path("", views.post_list, name="post-list"),
    path("post-detail/<int:pk>/", views.PostDetailView.as_view(), name="post-detail"),
    #path("post-detail/<int:pk>/", views.post_detail, name="post-detail"),
    path("draft-list/", views.DraftListView.as_view(), name="draft-list"),
    #path("draft-list/", views.draft_list, name="draft-list"),
    path("draft-detail/<int:pk>/", views.DraftDetailView.as_view(), name="draft-detail"),
    #path("draft-detail/<int:pk>/", views.draft_detail, name="draft-detail"),
    path("draft-publish/<int:pk>/", views.DraftPublishView.as_view(), name="draft-publish"),
    #path("draft-publish/<int:pk>/", views.draft_publish, name="draft-publish"),
    path("post-delete/<int:pk>/", views.PostDeleteView.as_view(), name="post-delete"),
    #path("post-delete/<int:pk>/", views.post_delete, name="post-delete"),
    path("post-create/", views.PostCreateView.as_view(), name="post-create"),
    #path("post-create/", views.post_create, name="post-create"),
    path("post-update/<int:pk>/", views.PostUpdateView.as_view(), name="post-update"),
    #path("post-update/<int:pk>/", views.post_update, name="post-update"),
]

templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Personal Blog</title>
        <link href="{% static 'blog/css/bootstrap.min.css' %}" rel="stylesheet">
        <link rel="stylesheet"
              href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
        <link rel="stylesheet" href="{% static 'blog/css/blog.css' %}">
    </head>
    <body>
        {% block bs_modal %}


        {% endblock bs_modal %}
        <div class="page-header">
            {% if user.is_authenticated %}
                <a href="{% url 'logout' %}" class="top-menu">
                    <span class="material-symbols-outlined lg-icons">logout</span>
                </a>
                <a href="{% url 'blog:draft-list' %}" class="top-menu">
                    <span class="material-symbols-outlined lg-icons">draft</span>
                </a>
                <a href="{% url 'blog:post-create' %}" class="top-menu">
                    <span class="material-symbols-outlined lg-icons">add</span>
                </a>
            {% else %}
                <a href="{% url 'login' %}" class="top-menu">
                    <span class="material-symbols-outlined lg-icons">login</span>
                </a>
            {% endif %}
            <h1>
                <a href="/">
                    <img src="{% static "blog/img/favicon.ico" %}" alt="Personal Blog" width="90px">
                    Personal Blog
                </a>
            </h1>
        </div>
        <div class="container content">
            {% block content %}
            {% endblock content %}
        </div>
        <script src="{% static 'blog/js/bootstrap.bundle.min.js' %}"></script>
    </body>
</html>

templates/blog/draft_detail.html
{% extends "blog/base.html" %}
{% block bs_modal %}
    <!-- Modal -->
    <div class="modal fade"
         id="deletePost"
         tabindex="-1"
         aria-labelledby="deletePostLabel"
         aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="deletePostLabel">Caution</h1>
                    <button type="button"
                            class="btn-close"
                            data-bs-dismiss="modal"
                            aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form action="{% url 'blog:post-delete' post.pk %}" method="post">
                        {% csrf_token %}
                        <h6>Are you sure you want to delete ?</h6>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                            <button type="submit" class="btn btn-danger">Delete</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock bs_modal %}
{% block content %}
    <div class="row">
        <div class="col">
            <div class="post">
                <h1>
                    <a href="#">{{ post.title }}</a>
                </h1>
                {% if user.is_authenticated %}
                    <div class="mt-2">
                        {% if post.published_at %}
                            <div class="date">{{ post.published_at }}</div>
                        {% else %}
                            <a href="{% url 'blog:draft-publish' post.pk %}" class="btn btn-success">Publish</a>
                        {% endif %}
                    </div>
                {% endif %}
                {% if user.is_authenticated %}
                    <div class="mt-2 my-2">
                        <a href="{% url 'blog:post-update' post.pk %}" class="btn btn-primary">Edit</a>
                        <!-- Button trigger modal -->
                        <button type="button"
                                class="btn btn-danger"
                                data-bs-toggle="modal"
                                data-bs-target="#deletePost">Delete</button>
                    </div>
                {% endif %}
                <div class="date author">@{{ post.author.username }}</div>
                <p>{{ post.content|safe }}</p>
            </div>
        </div>
    </div>
{% endblock content %}

templates/blog/draft_list.html
{% extends "blog/base.html" %}
{% block content %}
    <div class="row">
        <div class="col">
            {% for post in posts %}
                <div class="post">
                    {% if post.published_at %}
                    <div class="date">{{ post.published_at }}</div>
                    {% endif %}
                    <h1>
                        <a href="{% url 'blog:draft-detail' post.pk %}">{{ post.title }}</a>
                    </h1>
                    <div class="date author">@{{ post.author.username }}</div>
                    <p>
                        {{ post.content|striptags|truncatechars:200 }} <a href="{% url 'blog:draft-detail' post.pk %}">View more</a>
                    </p>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock content %}

templates/blog/post_create.html
{% extends "blog/base.html" %}
{% block content %}
    <form action=""
          method="post"
          class="post-form"
          enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-success">Save</button>
    </form>
{% endblock content %}

templates/blog/post_detail.html
{% extends "blog/base.html" %}
{% block bs_modal %}
    <!-- Modal -->
    <div class="modal fade"
         id="deletePost"
         tabindex="-1"
         aria-labelledby="deletePostLabel"
         aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="deletePostLabel">Caution</h1>
                    <button type="button"
                            class="btn-close"
                            data-bs-dismiss="modal"
                            aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form action="{% url 'blog:post-delete' post.pk %}" method="post">
                        {% csrf_token %}
                        <h6>Are you sure you want to delete ?</h6>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                            <button type="submit" class="btn btn-danger">Delete</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock bs_modal %}
{% block content %}
    <div class="row">
        <div class="col">
            <div class="post">
                <h1>
                    <a href="#">{{ post.title }}</a>
                </h1>
                <div class="date">{{ post.published_at }}</div>
                {% if user.is_authenticated %}
                    <div class="mt-2 my-2">
                        <a href="{% url 'blog:post-update' post.pk %}" class="btn btn-primary">Edit</a>
                        <!-- Button trigger modal -->
                        <button type="button"
                                class="btn btn-danger"
                                data-bs-toggle="modal"
                                data-bs-target="#deletePost">Delete</button>
                    </div>
                {% endif %}
                <div class="date author">@{{ post.author.username }}</div>
                <p>{{ post.content|safe|linebreaksbr }}</p>
            </div>
        </div>
    </div>
{% endblock content %}

templates/blog/post_list.html
{% extends "blog/base.html" %}
{% block content %}
    <div class="row">
        <div class="col">
            {% for post in posts %}
                <div class="post">
                    {% if post.published_at %}
                    <div class="date">{{ post.published_at }}</div>
                    {% endif %}
                    <h1>
                        <a href="{% url 'blog:post-detail' post.pk %}">{{ post.title }}</a>
                    </h1>
                    <div class="date author">@{{ post.author.username }}</div>
                    <p>
                        {{ post.content|striptags|truncatechars:200 }} <a href="{% url 'blog:post-detail' post.pk %}">View more</a>
                    </p>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock content %}